import re
import sys
import os

def printHeader(fread,fwrite):
	fr = open(fread,'r')
	buffer = fr.read()
	fr.close()
	fw = open(fwrite,'w')
	fw.write("/*\n*\tTest generated by:\n*\t\
Angelo Wong\n*\tYao Hao\n*\tLanyue Wang\n*\t\
of EECS 578 Fall 2012\n*/\n\n\n")
	fw.write(buffer)
	fw.write("\n! End includes\n\n")
	fw.write("\t.text\n\t.global main\n\n")
	fw.write("main:\n")
	fw.close()
