/*
*	Test generated by:
*	Angelo Wong
*	Yao Hao
*	Lanyue Wang
*	of EECS 578 Fall 2012
*/


#define SCONTEXT PCONTEXT

#define	MAIN_PAGE_NUCLEUS_ALSO
#define	MAIN_PAGE_HV_ALSO
!#define	N_CPUS	64
#define	ENABLE_T0_Fp_exception_ieee_754_0x21
#define	ENABLE_T0_Fp_exception_other_0x22
#define	ENABLE_T0_Fp_disabled_0x20
#define	ENABLE_T0_Illegal_instruction_0x10
#define	ENABLE_T1_Illegal_instruction_0x10
#define	ENABLE_HT0_Illegal_instruction_0x10
#define	ENABLE_HT1_Illegal_instruction_0x10
#define	ENABLE_T0_Clean_Window_0x24
!#define	THREAD_COUNT	64
#define	THREAD_STRIDE	1
#define	SKIP_TRAPCHECK
#define USE_MPGEN_TRAPS

#include "boot.s"
#include "hboot.s"
#include "mmu_custom_intr_handlers.s"
#include "peu_defines.h"

! End includes

	.text
	.global main

main:
	th_fork(proc,%l0)

proc_0:
	ta	T_CHANGE_PRIV
	set	done_flags,%g1
	mov	1,%g2
	st	%g2,[%g1+0x00]
	wrpr	%g0,7,%cleanwin
	wr	%g0,0x80,%asi
	membar #Sync
	ldx	[%g1+0x70],%o0
	add	%g1,0x1021,%i3
	add	%g1,0x131e,%i0
	add	%g1,0x1ebe,%i2
	ldx	[%g1+0x70],%l5
	ldx	[%g1+0x70],%i5
	add	%g1,0x17cf,%i1
	add	%g1,0x1b3e,%i4
	ldx	[%g1+0x70],%l4
	ldx	[%g1+0x70],%i6
	ldx	[%g1+0x70],%i7
	add	%g1,0x125c,%i5
	ldx	[%g1+0x70],%l7
	add	%g1,0x161d,%i3
	ldx	[%g1+0x80],%i2
	ldx	[%g1+0x70],%i4
	membar #Sync
	add	%g1,0x13ad,%i0
	add	%g1,0x1d3f,%i5
	add	%g1,0x1e28,%i7
	ldx	[%g1+0x80],%l0
	add	%g1,0x18ca,%i7
	add	%g1,0x1764,%i7
	add	%g1,0x131b,%i4
	stx	%o4,[%g1+0x70]
	ldx	[%g1+0x80],%i1
	add	%g1,0x101a,%i0
	ldx	[%g1+0x70],%i5
	stx	%o2,[%g1+0x80]
	ldx	[%g1+0x70],%i7
	add	%g1,0x14c2,%i3
	add	%g1,0x1727,%i6
	stx	%l1,[%g1+0x70]
	add	%g1,0x1683,%i4
	add	%g1,0x15fe,%i0
	add	%g1,0x1835,%i3
	ldx	[%g1+0x70],%o6
	ldx	[%g1+0x70],%i1
	ldx	[%g1+0x70],%i4
	ldx	[%g1+0x70],%i1
	membar #Sync
	ldx	[%g1+0x80],%i5
	ldx	[%g1+0x80],%i3
	add	%g1,0x1ee6,%i2
	stx	%o7,[%g1+0x80]
	ldx	[%g1+0x80],%i6
	ldx	[%g1+0x70],%i7
	ldx	[%g1+0x70],%i6
	ldx	[%g1+0x70],%o1
	ldx	[%g1+0x80],%i7
	ldx	[%g1+0x70],%i3
	add	%g1,0x11ee,%i0
	ldx	[%g1+0x70],%l2
	ldx	[%g1+0x80],%i1
	add	%g1,0x1aaa,%i2
	add	%g1,0x13e5,%i4
	stx	%o3,[%g1+0x70]
	add	%g1,0x11d9,%i5
	ldx	[%g1+0x80],%i3
	add	%g1,0x17cd,%i6
	stx	%o5,[%g1+0x70]
	add	%g1,0x146d,%i7
	add	%g1,0x1aaf,%i4
	ldx	[%g1+0x80],%i7
	stx	%o1,[%g1+0x80]
	ldx	[%g1+0x80],%i0
	ldx	[%g1+0x80],%i4
	ldx	[%g1+0x70],%i4
	stx	%l3,[%g1+0x80]
	ldx	[%g1+0x70],%i6
	add	%g1,0x16d6,%i0
	add	%g1,0x16a4,%i3
	stx	%o0,[%g1+0x80]
	add	%g1,0x151e,%i2
	add	%g1,0x1679,%i4
	ldx	[%g1+0x70],%i0
	ldx	[%g1+0x70],%l6
	ldx	[%g1+0x70],%i3
	add	%g1,0x18cc,%i3
	ldx	[%g1+0x80],%i4
	ldx	[%g1+0x80],%l1
	add	%g1,0x17e0,%i5
	ldx	[%g1+0x80],%i4
	add	%g1,0x15ef,%i7
	stx	%o5,[%g1+0x70]
	add	%g1,0x1c26,%i5
	add	%g1,0x12e2,%i3
	add	%g1,0x1bfa,%i3
	stx	%o0,[%g1+0x80]
	add	%g1,0x1a6c,%i3
	ldx	[%g1+0x70],%i6
	ldx	[%g1+0x70],%i5
	ldx	[%g1+0x80],%l0
	ldx	[%g1+0x70],%i7
	ldx	[%g1+0x70],%i0
	ldx	[%g1+0x70],%i0
	stx	%o6,[%g1+0x80]
	ldx	[%g1+0x80],%i6
	add	%g1,0x179b,%i5
	add	%g1,0x1cfc,%i5
	membar #Sync
	ta	GOOD_TRAP
	nop

done_flags:
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.word	0
	.align	8
